name: 🚀 Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Messi123!@#
          POSTGRES_DB: football_connects_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: "&)ci+xil%vn=vy8*gv$s5)ts5x70^ky*^5hwed*%@1k2zrqi0)"
      DEBUG: True
      DB_NAME: football_connects_db
      DB_USER: postgres
      DB_PASSWORD: Messi123!@#
      DB_HOST: localhost
      DB_PORT: 5432
      REDIS_URL: redis://127.0.0.1:6379/1

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 💾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⏳ Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: 🛠️ Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: ✅ Run tests
        run: |
          python manage.py test
